config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'chatrooms#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, length: {minimum: 3, maximum: 15},
            uniqueness: {case_sensitive: false }
  has_many :messages
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def required_user
    if !logged_in?
      flash[:error] = "You must be logged in to perfrom that action!"
      redirect_to login_path
    end
  end

end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :required_user

  def index
    @message = Message.new
    @messages = Message.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :required_user

  def create
    message = current_user.messages.build(message_params)
    if message.save
      redirect_to root_path
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [:new, :create]


  def new

  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Welcome back to Message Me"
      redirect_to root_path
    else
      flash.now[:error] = "There was a problem with your login info"
      render 'new'
    end
  end

  def update

  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have been successfully logged out"
    redirect_to login_path
  end

  private

    def logged_in_redirect
      if logged_in?
        flash[:error] = "You are already logged in!"
        redirect_to root_path
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/chatrooms/index.html.erb
<h3 class="ui center aligned medium icon header">
  <i class="circular at inverted blue icon"></i>
  Messenger
</h3>

<div class="ui column grid" style="margin-top: 1.5rem">

  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <a class="ui blue ribbon label">Activity Feed</a>
        <div class="ui feed">
          <%= render "messages/messages" %>
        </div>
      </div>
      <div class="extra content">
        <%= form_for(@message, html: {class: "ui reply form", role: "form"}, url: message_path) do |f| %>
          <div class="field">
            <div class="ui fluid icon input">
              <%= f.text_field :body %>
              <%= f.button '<i class="bordered inverted blue edit icon"></i>'.html_safe %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui secondary vertical pointing menu">
          <a class="active item">
            Home
          </a>
          <a class="item">
            Messages
          </a>
          <a class="item">
            Friends
          </a>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>
  <div class="ui <%= message_type %> message transition">
    <i class="close icon"></i>
    <div class="header">
      <%= message_content %>
    </div>
  </div>

<% end %>

app/views/layouts/_nav.html.erb
<div class="ui small menu inverted">
  <div class="ui container">
    <%= link_to "Chatroom", root_path, class: "item" %>
    <%= link_to "Messages", root_path, class: "item" %>
    <div class="right menu">
      <div class="ui dropdown item">
        Account <i class="dropdown icon"></i>
        <div class="menu">
          <% if logged_in? %>
            <%= link_to "Logout", logout_path, method: :delete, class: "item" %>
          <% else %>
          <%= link_to "Login", login_path, class: "item" %>
          <% end %>
        </div>
      </div>
      <% if !logged_in? %>
      <div class="item">
        <%= link_to "Login", login_path, class: "ui primary button" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <div class="ui container">
      <%= render "layouts/messages" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_messages.html.erb
<% @messages.each do |message| %>
  <div class="event">
    <div class="content">
      <div class="summary">
         <em><%= message.user.username %>:</em> <%= message.body %>
      </div>
    </div>
  </div>
<% end %>

app/views/messages/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>